- name: Download AriaNg
  get_url:
    url: "https://github.com/mayswind/AriaNg/releases/download/1.3.7/AriaNg-1.3.7.zip"
    dest: "~/aria2/AriaNg-1.3.7.zip"

- name: Unzip AriaNg
  unarchive:
    src: "~/aria2/AriaNg-1.3.7.zip"
    dest: "~/aria2/www"
    remote_src: yes

- name: Find the AriaNg JS file
  find:
    paths: "~/aria2/www/ariang/js"
    patterns: "aria-ng-*.min.js"
  register: arian_js_files

- name: Set defaults in AriaNg JS file
  replace:
    path: "{{ item.path }}"
    regexp: 'rpcPort:"6800"'
    replace: 'rpcPort:"443"'
  with_items: "{{ arian_js_files.files }}"

- name: Set rpcInterface in AriaNg JS file
  replace:
    path: "{{ item.path }}"
    regexp: 'rpcInterface:""'
    replace: 'rpcInterface:"aria2c/jsonrpc"'
  with_items: "{{ arian_js_files.files }}"

- name: Set secret in AriaNg JS file
  replace:
    path: "{{ item.path }}"
    regexp: 'secret:""'
    replace: 'secret:"{{ aria2c_secret }}"'
  with_items: "{{ arian_js_files.files }}"

- name: Set rpcHost in AriaNg JS file
  replace:
    path: "{{ item.path }}"
    regexp: 'rpcHost:""'
    replace: 'rpcHost:"{{ aria2c_host }}"'
  with_items: "{{ arian_js_files.files }}"

- name: Set protocol in AriaNg JS file
  replace:
    path: "{{ item.path }}"
    regexp: 'protocol:""'
    replace: 'protocol:"https"'
  with_items: "{{ arian_js_files.files }}"
