- name: Download metube source
  get_url:
    url: "https://github.com/alexta69/metube/archive/refs/heads/master.zip"
    dest: "/tmp/metube-master.zip"
    mode: '0644'
  delegate_to: localhost

- name: Unzip metube source
  unarchive:
    src: "/tmp/metube-master.zip"
    dest: "/tmp"
    remote_src: no
  delegate_to: localhost

- name: Build Angular app locally
  docker_container:
    name: build_angular_app
    image: node:lts-alpine
    working_dir: /build/ui
    volumes:
      - /tmp/metube-master:/build
    entrypoint: sh -c 'npm ci && node_modules/.bin/ng build --configuration production && rm -rf node_modules .angular'
    state: started
    cleanup: yes
  delegate_to: localhost

- name: Copy metube source to remote
  copy:
    src: /tmp/metube-master
    dest: ~/metube-master
    mode: '0755'

- name: Install pipenv
  pip:
    name: pipenv
    executable: pip3

- name: Install dependencies with pipenv
  command: pipenv install
  args:
    chdir: ~/metube-master

- name: Create .htpasswd file
  command: htpasswd -bc {{ ansible_env.HOME }}/metube-master/.htpasswd {{ ansible_user }} {{ metube_password }}

- name: Copy metube.conf
  template:
    src: metube.conf
    dest: "{{ ansible_env.HOME }}/.apps/nginx/proxy.d/metube.conf"

- name: Copy metube.service
  template:
    src: metube.service
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/metube.service"

- name: Enable and start metube service
  systemd:
    name: metube
    enabled: yes
    state: started
    user: yes
