- name: Restart nginx
  command: app-nginx restart

- name: Enable and restart metube
  shell: |
    systemctl --user daemon-reload &&
    systemctl --user enable metube &&
    systemctl --user restart metube