---
- name: Ensure ErsatzTV directory exists
  file:
    path: ~/ersatztv
    state: directory

- name: Download ErsatzTV
  get_url:
    url: https://github.com/ErsatzTV/ErsatzTV/releases/download/v0.8.7-beta/ErsatzTV-v0.8.7-beta-linux-x64.tar.gz
    dest: ~/ersatztv/ErsatzTV.tar.gz

- name: Extract ErsatzTV
  unarchive:
    src: ~/ersatztv/ErsatzTV.tar.gz
    dest: ~/ersatztv
    remote_src: yes

- name: Copy ersatztv.service
  template:
    src: ersatztv.service
    dest: ~/.config/systemd/user/ersatztv.service
  notify:
    - Enable and restart ersatztv

- name: Copy ersatztv.conf
  template:
    src: ersatztv.conf
    dest: ~/.apps/nginx/proxy.d/ersatztv.conf
  notify:
    - Restart nginx