---
- name: Ensure ErsatzTV directory exists
  file:
    path: ~/ersatztv
    state: directory

- name: Download ErsatzTV
  get_url:
    url: https://github.com/ErsatzTV/ErsatzTV/releases/download/v0.8.7-beta/ErsatzTV-v0.8.7-beta-linux-x64.tar.gz
    dest: ~/ersatztv/ErsatzTV.tar.gz

- name: Extract ErsatzTV
  unarchive:
    src: ~/ersatztv/ErsatzTV.tar.gz
    dest: ~/ersatztv
    remote_src: yes

- name: Ensure ErsatzTV service is enabled and started
  systemd:
    name: ersatztv
    state: started
    enabled: yes
