---
- name: Ensure ErsatzTV directory exists
  file:
    path: ~/ersatztv
    state: directory

- name: Download ErsatzTV
  get_url:
    url: https://github.com/ErsatzTV/ErsatzTV/releases/download/v0.8.7-beta/ErsatzTV-v0.8.7-beta-linux-x64.tar.gz
    dest: ~/ersatztv/ErsatzTV.tar.gz

- name: Extract ErsatzTV
  unarchive:
    src: ~/ersatztv/ErsatzTV.tar.gz
    dest: ~/ersatztv
    remote_src: yes

- name: Restart ErsatzTV service
  command: systemctl --user restart ersatztv
  notify: Restart ErsatzTV

- name: Ensure ErsatzTV service is enabled and started
  systemd:
    name: ersatztv
    state: started
    enabled: yes

- name: Ensure Nginx configuration directory exists
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: Deploy ErsatzTV Nginx configuration
  template:
    src: ersatztv_nginx.conf.j2
    dest: /etc/nginx/conf.d/ersatztv.conf
  notify: Restart Nginx
