- name: Download AriaNg
  get_url:
    url: "https://github.com/mayswind/AriaNg/releases/download/1.3.7/AriaNg-1.3.7.zip"
    dest: "~/AriaNg-1.3.7.zip"

- name: Unzip AriaNg
  unarchive:
    src: "~/AriaNg-1.3.7.zip"
    dest: "~/www/ariang"
    remote_src: yes

- name: Find the AriaNg JS file
  find:
    paths: "~/www/ariang/js"
    patterns: "aria-ng-*.min.js"
  register: ariang_js_files

- name: Replace values in AriaNg JS file
  replace:
    path: "{{ item.0.path }}"
    regexp: "{{ item.1.regexp }}"
    replace: "{{ item.1.replace }}"
  loop: "{{ ariang_js_files.files | product(replace_pairs) | list }}"
  vars:
    replace_pairs:
      - { regexp: 'rpcPort:"6800"', replace: 'rpcPort:"443"' }
      - { regexp: 'rpcInterface:""', replace: 'rpcInterface:"aria2c/jsonrpc"' }
      - { regexp: 'secret:""', replace: 'secret:"{{ aria2c_secret }}"' }
      - { regexp: 'rpcHost:""', replace: 'rpcHost:"{{ aria2c_host }}"' }
      - { regexp: 'protocol:""', replace: 'protocol:"https"' }
