- name: Copy aria2.service
  template:
    src: aria2.service
    dest: ~/.config/systemd/user/aria2c.service
  notify:
    - Daemon reload
    - Enable and start aria2c

- name: Copy aria2c.conf
  template:
    src: aria2c.conf
    dest: ~/.apps/nginx/proxy.d/aria2c.conf
  notify:
    - Restart nginx