- name: Download metube source
  get_url:
    url: "https://github.com/alexta69/metube/archive/refs/heads/master.zip"
    dest: "/tmp/metube-master.zip"
    mode: '0644'
  delegate_to: localhost

- name: Unzip metube source
  unarchive:
    src: "/tmp/metube-master.zip"
    dest: "/tmp"
    remote_src: no
  delegate_to: localhost

- name: Build Angular app locally
  ansible.builtin.shell:
    cmd: >
      docker run --name build_angular_app -w /build/ui -v /tmp/metube-master:/build node:lts-alpine 
      sh -c 'npm ci && node_modules/.bin/ng build --configuration production && rm -rf node_modules .angular'
    executable: /bin/bash
  delegate_to: localhost

- name: Copy metube source to remote
  copy:
    src: /tmp/metube-master
    dest: ~/metube-master
    mode: '0755'

- name: Install pipenv
  pip:
    name: pipenv

- name: Install dependencies with pipenv
  command: pipenv install
  args:
    chdir: ~/metube-master

- name: Create .htpasswd file
  command: htpasswd -bc {{ ansible_env.HOME }}/metube-master/.htpasswd {{ ansible_user }} {{ metube_password }}

- name: Copy metube.service
  template:
    src: metube.service
    dest: ~/.config/systemd/user/metube.service
  notify:
    - Daemon reload
    - Enable and start aria2c

- name: Copy metube.conf
  template:
    src: metube.conf
    dest: ~/.apps/nginx/proxy.d/metube.conf
  notify:
    - Restart nginx

- name: Restart nginx
  command: app-nginx restart

- name: Daemon reload
  command: systemctl --user daemon-reload

- name: Enable and start metube
  command: systemctl --user enable --now metube
